export const levels = [
  [
    { words: ["Mesa", "Cadeira", "Sofa", "Estante"], category: "Moveis de casa", difficulty: "facil", color: "#f9df6d" },
    { words: ["Arroz", "Massa", "Batata", "Pao"], category: "Acompanhamentos comuns", difficulty: "facil", color: "#a0c35a" },
    { words: ["Azul", "Verde", "Preto", "Branco"], category: "Cores", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Ler", "Ouvir", "Ver", "Falar"], category: "Acoes do dia a dia", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Garfo", "Faca", "Colher", "Prato"], category: "Mesa posta", difficulty: "facil", color: "#f9df6d" },
    { words: ["Manha", "Tarde", "Noite", "Madrugada"], category: "Partes do dia", difficulty: "facil", color: "#a0c35a" },
    { words: ["Norte", "Sul", "Este", "Oeste"], category: "Pontos cardeais", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Metro", "Comboio", "Autocarro", "Eletrico"], category: "Transportes publicos", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Lisboa", "Porto", "Coimbra", "Faro"], category: "Cidades portuguesas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Tejo", "Douro", "Sado", "Mondego"], category: "Rios de Portugal", difficulty: "medio", color: "#a0c35a" },
    { words: ["Rosa", "Cravo", "Tulipa", "Lirio"], category: "Flores", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Fino", "Bica", "Galao", "Garoto"], category: "Pedidos de cafe ou cerveja", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Camisa", "Casaco", "Saia", "Calca"], category: "Pecas de roupa", difficulty: "facil", color: "#f9df6d" },
    { words: ["Manga", "Gola", "Punho", "Costura"], category: "Partes de roupa", difficulty: "medio", color: "#a0c35a" },
    { words: ["Bota", "Sapato", "Sandalia", "Tenis"], category: "Calcado", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Cinto", "Lenco", "Chapeu", "Relogio"], category: "Acessorios", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Soma", "Divisao", "Produto", "Resto"], category: "Matematica basica", difficulty: "medio", color: "#f9df6d" },
    { words: ["Verbo", "Nome", "Adjetivo", "Adverbio"], category: "Classes de palavras", difficulty: "medio", color: "#a0c35a" },
    { words: ["Ponto", "Virgula", "Aspas", "Travessao"], category: "Pontuacao", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Regua", "Compasso", "Esquadro", "Transferidor"], category: "Geometria", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Bifana", "Prego", "Rissol", "Croquete"], category: "Comida de cafe", difficulty: "facil", color: "#f9df6d" },
    { words: ["Bacalhau", "Polvo", "Dourada", "Sardinha"], category: "Peixe na mesa portuguesa", difficulty: "facil", color: "#a0c35a" },
    { words: ["Assar", "Ferver", "Grelhar", "Estufar"], category: "Formas de cozinhar", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Salsa", "Coentros", "Louro", "Alecrim"], category: "Ervas aromaticas", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Euro", "Libra", "Dolar", "Iene"], category: "Moedas atuais", difficulty: "facil", color: "#f9df6d" },
    { words: ["Escudo", "Real", "Pataca", "Cruzado"], category: "Moedas antigas ou historicas", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Massa", "Guito", "Pilim", "Arame"], category: "Giria para dinheiro", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Banco", "Caixa", "Troco", "Juro"], category: "Dinheiro e banca", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Canto", "Livre", "Fora", "Penalty"], category: "Lances de futebol", difficulty: "facil", color: "#f9df6d" },
    { words: ["Rede", "Baliza", "Campo", "Bancada"], category: "Espacos de jogo", difficulty: "facil", color: "#a0c35a" },
    { words: ["Sueca", "Bisca", "Copas", "Burro"], category: "Jogos de cartas em Portugal", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Xadrez", "Damas", "Domino", "Gamao"], category: "Jogos de tabuleiro", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Janela", "Porta", "Varanda", "Chamine"], category: "Aberturas de casa", difficulty: "facil", color: "#f9df6d" },
    { words: ["Tijolo", "Cimento", "Areia", "Gesso"], category: "Construcao", difficulty: "medio", color: "#a0c35a" },
    { words: ["Cano", "Ralo", "Sifao", "Torneira"], category: "Canalizacao", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Folha", "Linha", "Margem", "Capa"], category: "Caderno", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Agudo", "Grave", "Til", "Cedilha"], category: "Sinais da escrita portuguesa", difficulty: "medio", color: "#f9df6d" },
    { words: ["Fado", "Vira", "Chula", "Corridinho"], category: "Musica e danca tradicional", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Palco", "Plateia", "Camarote", "Bastidor"], category: "Espetaculo", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Tomo", "Nota", "Tempo", "Ritmo"], category: "Musica ou leitura", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Guarda", "Faro", "Lagos", "Braga"], category: "Cidades que tambem sao palavras", difficulty: "medio", color: "#f9df6d" },
    { words: ["Visao", "Audicao", "Tato", "Olfato"], category: "Sentidos", difficulty: "facil", color: "#a0c35a" },
    { words: ["Vence", "Bate", "Mata", "Derrota"], category: "Ganha contra alguem", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Raso", "Santo", "Livre", "Morto"], category: "Espirito ____", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Imperial", "Fino", "Caneca", "Girafa"], category: "Cerveja em Portugal", difficulty: "medio", color: "#f9df6d" },
    { words: ["Carioca", "Bica", "Abatanado", "Pingado"], category: "Cafe em Portugal", difficulty: "medio", color: "#a0c35a" },
    { words: ["Branco", "Tinto", "Verde", "Rose"], category: "Tipos de vinho", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Reserva", "Colheita", "Garrafa", "Rolha"], category: "Vinho e adega", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Ouro", "Prata", "Cobre", "Bronze"], category: "Metais e medalhas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Jade", "Safira", "Rubi", "Onix"], category: "Pedras", difficulty: "medio", color: "#a0c35a" },
    { words: ["Azoto", "Helio", "Argon", "Xenon"], category: "Gases nobres ou elementos", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Atlas", "Andes", "Alpes", "Pirenes"], category: "Cadeias montanhosas", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Peao", "Torre", "Bispo", "Cavalo"], category: "Pecas de xadrez", difficulty: "facil", color: "#f9df6d" },
    { words: ["Rei", "Dama", "Valete", "As"], category: "Cartas de figura ou valor", difficulty: "facil", color: "#a0c35a" },
    { words: ["Roque", "Cheque", "Mate", "Gambito"], category: "Termos de xadrez", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Paus", "Ouros", "Copas", "Espadas"], category: "Naipes", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Pai", "Mae", "Tio", "Prima"], category: "Familia", difficulty: "facil", color: "#f9df6d" },
    { words: ["Sogro", "Genro", "Nora", "Cunhado"], category: "Familia por casamento", difficulty: "medio", color: "#a0c35a" },
    { words: ["Berco", "Fralda", "Chucha", "Biberon"], category: "Bebe", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Avos", "Netos", "Pais", "Filhos"], category: "Geracoes", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Prego", "Alho", "Pente", "Serra"], category: "Coisas com dentes ou cabeca", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Cabeca", "Olho", "Mao", "Pe"], category: "Partes do corpo em expressoes", difficulty: "facil", color: "#a0c35a" },
    { words: ["Vento", "Ladeira", "Cabra", "Lata"], category: "Pe de ____", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Mesa", "Cadeira", "Banco", "Sofa"], category: "Onde se senta ou apoia", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Domingo", "Segunda", "Terca", "Quinta"], category: "Dias da semana", difficulty: "facil", color: "#f9df6d" },
    { words: ["Domino", "Segurar", "Terceto", "Quintal"], category: "Comecam como dias da semana", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Nova", "Cheia", "Minguante", "Crescente"], category: "Fases da Lua", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Hora", "Minuto", "Segundo", "Instante"], category: "Tempo", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Brasa", "Bras", "Lagareiro", "Gomes"], category: "Bacalhau a ____", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Arroz", "Leite", "Aletria", "Fatia"], category: "Doces tradicionais", difficulty: "medio", color: "#a0c35a" },
    { words: ["Nata", "Ovos", "Mel", "Acucar"], category: "Ingredientes de doce", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Doce", "Salgado", "Amargo", "Acido"], category: "Sabores", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Cisma", "Teima", "Birra", "Capricho"], category: "Insistencia", difficulty: "medio", color: "#f9df6d" },
    { words: ["Calma", "Sereno", "Manso", "Quieto"], category: "Sem agitacao", difficulty: "medio", color: "#a0c35a" },
    { words: ["Afoito", "Audaz", "Bravio", "Valente"], category: "Corajoso", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Sisudo", "Severo", "Austero", "Grave"], category: "Muito serio", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Mira", "Alvo", "Ponto", "Centro"], category: "Para onde se aponta", difficulty: "medio", color: "#f9df6d" },
    { words: ["Linha", "Rede", "Poste", "Trave"], category: "Desporto e limites", difficulty: "medio", color: "#a0c35a" },
    { words: ["Cerca", "Muro", "Grade", "Vedacao"], category: "Separar espacos", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Finta", "Passe", "Drible", "Remate"], category: "Gestos de jogo", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Foice", "Enxada", "Ancinho", "Arado"], category: "Ferramentas agricolas", difficulty: "medio", color: "#f9df6d" },
    { words: ["Centeio", "Milho", "Trigo", "Aveia"], category: "Cereais", difficulty: "facil", color: "#a0c35a" },
    { words: ["Vindima", "Poda", "Rega", "Sementeira"], category: "Trabalhos do campo", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Varanda", "Quintal", "Celeiro", "Curral"], category: "Espacos da casa ou quinta", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Tomo", "Volume", "Capitulo", "Indice"], category: "Livro", difficulty: "medio", color: "#f9df6d" },
    { words: ["Autor", "Leitor", "Editor", "Revisor"], category: "Pessoas ligadas ao livro", difficulty: "facil", color: "#a0c35a" },
    { words: ["Prosa", "Verso", "Rima", "Estrofe"], category: "Literatura", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Bilhete", "Carta", "Recado", "Convite"], category: "Textos curtos", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Azulejo", "Calcada", "Varina", "Pregao"], category: "Lisboa tradicional", difficulty: "medio", color: "#f9df6d" },
    { words: ["Ribeira", "Douro", "Caves", "Aliados"], category: "Porto", difficulty: "medio", color: "#a0c35a" },
    { words: ["Capa", "Queima", "Lente", "Republica"], category: "Coimbra academica", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Nata", "Ovos", "Leite", "Canela"], category: "Ingredientes de doces", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Bordo", "Popa", "Proa", "Leme"], category: "Barco", difficulty: "medio", color: "#f9df6d" },
    { words: ["Cabo", "Baia", "Foz", "Praia"], category: "Costa", difficulty: "facil", color: "#a0c35a" },
    { words: ["Rede", "Isca", "Anzol", "Cana"], category: "Pesca", difficulty: "facil", color: "#b0c4ef" },
    { words: ["Rumo", "Carta", "Astro", "Bussola"], category: "Navegacao", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Siso", "Molar", "Canino", "Incisivo"], category: "Dentes", difficulty: "medio", color: "#f9df6d" },
    { words: ["Coroa", "Raiz", "Esmalte", "Polpa"], category: "Partes do dente", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Trono", "Ceptro", "Reino", "Monarca"], category: "Realeza", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Caule", "Folha", "Fruto", "Flor"], category: "Planta", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Acordo", "Pacto", "Tratado", "Convenio"], category: "Combinacao formal", difficulty: "medio", color: "#f9df6d" },
    { words: ["Modo", "Jeito", "Forma", "Maneira"], category: "Como se faz algo", difficulty: "facil", color: "#a0c35a" },
    { words: ["Reparo", "Conserto", "Emenda", "Arranjo"], category: "Correcao", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Jura", "Voto", "Promessa", "Palavra"], category: "Compromisso", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Malha", "Rede", "Trama", "Tecido"], category: "Entrecruzamento", difficulty: "medio", color: "#f9df6d" },
    { words: ["Web", "Site", "Link", "Browser"], category: "Internet", difficulty: "facil", color: "#a0c35a" },
    { words: ["Enredo", "Intriga", "Plano", "Conluio"], category: "Historia ou conspiracao", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Lance", "Jogada", "Ponto", "Partida"], category: "Termos de jogo", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Basto", "Vasto", "Largo", "Amplo"], category: "Grande ou espacoso", difficulty: "medio", color: "#f9df6d" },
    { words: ["Braga", "Chaves", "Lamego", "Viseu"], category: "Cidades do norte e centro", difficulty: "medio", color: "#a0c35a" },
    { words: ["Praca", "Terreiro", "Adro", "Rossio"], category: "Espaco publico", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Imenso", "Enorme", "Colossal", "Gigante"], category: "Muito grande", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Quina", "Canto", "Aresta", "Vertice"], category: "Geometria com pontas", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Escudo", "Cruz", "Hino", "Bandeira"], category: "Simbolos nacionais", difficulty: "medio", color: "#a0c35a" },
    { words: ["Quadra", "Soneto", "Ode", "Haiku"], category: "Formas poeticas", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Ponta", "Gume", "Fio", "Lamina"], category: "Extremidade cortante", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Engodo", "Logro", "Embuste", "Ardil"], category: "Engano", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Rato", "Tecla", "Ecra", "Pasta"], category: "Computador", difficulty: "facil", color: "#a0c35a" },
    { words: ["Raia", "Linha", "Limite", "Fronteira"], category: "Separacao", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Bago", "Grao", "Semente", "Pevide"], category: "Coisas pequenas de fruto", difficulty: "medio", color: "#ba81c5" },
  ],
  [
    { words: ["Ermo", "Baldio", "Charneca", "Mato"], category: "Terrenos pouco tratados", difficulty: "medio", color: "#f9df6d" },
    { words: ["Tojo", "Urze", "Giesta", "Esteva"], category: "Arbustos portugueses", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Elmo", "Cota", "Escudo", "Lanca"], category: "Equipamento medieval", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Saco", "Mala", "Bolsa", "Cesto"], category: "Onde se transporta algo", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Geada", "Orvalho", "Nevoeiro", "Granizo"], category: "Fenomenos meteorologicos", difficulty: "medio", color: "#f9df6d" },
    { words: ["Xavega", "Cerco", "Arrasto", "Palangre"], category: "Artes de pesca", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Nave", "Abside", "Altar", "Sacristia"], category: "Partes de uma igreja", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Nortada", "Suao", "Levante", "Terral"], category: "Ventos em Portugal", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Carda", "Fuso", "Meada", "Tear"], category: "Trabalho textil tradicional", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Infusa", "Caneco", "Odre", "Cantaro"], category: "Recipientes tradicionais", difficulty: "dificil", color: "#a0c35a" },
    { words: ["Rabelo", "Moliceiro", "Varino", "Saveiro"], category: "Embarcacoes tradicionais", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Castanha", "Noz", "Amendoa", "Avela"], category: "Frutos secos", difficulty: "facil", color: "#ba81c5" },
  ],
  [
    { words: ["Algar", "Dolina", "Lapa", "Gruta"], category: "Formacoes de relevo carsico", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Dobre", "Repique", "Badalada", "Trindades"], category: "Toques de sino", difficulty: "muito dificil", color: "#a0c35a" },
    { words: ["Adarga", "Elmo", "Cota", "Broquel"], category: "Protecao medieval", difficulty: "muito dificil", color: "#b0c4ef" },
    { words: ["Quina", "Zimbo", "Sestro", "Eivar"], category: "Palavras portuguesas raras", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Arrulho", "Bramido", "Chilreio", "Relincho"], category: "Vozes de animais", difficulty: "dificil", color: "#f9df6d" },
    { words: ["Alqueire", "Almude", "Arratel", "Covado"], category: "Medidas portuguesas antigas", difficulty: "muito dificil", color: "#a0c35a" },
    { words: ["Sapal", "Paul", "Varzea", "Leziria"], category: "Terrenos humidos", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Fole", "Tenaz", "Aticador", "Trempe"], category: "Utensilios de lareira", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Galinha", "Pato", "Peru", "Ganso"], category: "Aves de capoeira", difficulty: "facil", color: "#f9df6d" },
    { words: ["Estrela", "Geres", "Lousa", "Monchique"], category: "Serras portuguesas", difficulty: "medio", color: "#a0c35a" },
    { words: ["Coxia", "Ribalta", "Proscenio", "Fosso"], category: "Partes de um teatro", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Cicero", "Gralha", "Versal", "Vinheta"], category: "Termos de tipografia", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Agulha", "Dedal", "Tesoura", "Alfinete"], category: "Acessorios de costura", difficulty: "facil", color: "#f9df6d" },
    { words: ["Flauta", "Oboe", "Fagote", "Clarinete"], category: "Instrumentos de sopro de madeira", difficulty: "medio", color: "#a0c35a" },
    { words: ["Javali", "Texugo", "Gineta", "Corco"], category: "Mamiferos selvagens de Portugal", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Ataque", "Regra", "Peso", "Baixo"], category: "Formam palavra com contra-", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Lima", "Limao", "Tangerina", "Toranja"], category: "Frutos citricos", difficulty: "facil", color: "#f9df6d" },
    { words: ["Faial", "Corvo", "Graciosa", "Terceira"], category: "Ilhas dos Acores", difficulty: "medio", color: "#a0c35a" },
    { words: ["Couraca", "Grevas", "Manoplas", "Viseira"], category: "Pecas de uma armadura", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Cabecas", "Nozes", "Mares", "Luz"], category: "Formam palavra com quebra-", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Pombo", "Pardal", "Melro", "Gaivota"], category: "Aves urbanas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Evaporacao", "Condensacao", "Precipitacao", "Infiltracao"], category: "Processos do ciclo da agua", difficulty: "medio", color: "#a0c35a" },
    { words: ["Objetiva", "Diafragma", "Obturador", "Tripe"], category: "Elementos de fotografia", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Quedas", "Brisas", "Choques", "Raios"], category: "Formam palavra com para-", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Broa", "Regueifa", "Carcaca", "Bijou"], category: "Paes portugueses", difficulty: "facil", color: "#f9df6d" },
    { words: ["Cirro", "Estrato", "Cumulo", "Nimbo"], category: "Tipos de nuvem", difficulty: "medio", color: "#a0c35a" },
    { words: ["Aguia", "Falcao", "Acor", "Milhafre"], category: "Aves de rapina", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Azimute", "Meridiano", "Paralelo", "Legenda"], category: "Termos de cartografia", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Sobreiro", "Azinheira", "Medronheiro", "Carvalho"], category: "Arvores comuns em Portugal", difficulty: "facil", color: "#f9df6d" },
    { words: ["Arriba", "Restinga", "Tombolo", "Cordao"], category: "Formacoes costeiras", difficulty: "medio", color: "#a0c35a" },
    { words: ["Caravela", "Escuna", "Brigue", "Lugre"], category: "Embarcacoes a vela", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Barometro", "Higrometro", "Anemometro", "Pluviometro"], category: "Instrumentos meteorologicos", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Ganga", "Veludo", "Cetim", "Linho"], category: "Tecidos", difficulty: "facil", color: "#f9df6d" },
    { words: ["Cratera", "Caldeira", "Fumarola", "Cone"], category: "Formacoes vulcanicas", difficulty: "medio", color: "#a0c35a" },
    { words: ["Abertura", "Aria", "Recitativo", "Libreto"], category: "Partes de uma opera", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Astrolabio", "Sextante", "Quadrante", "Balestilha"], category: "Instrumentos de navegacao astronomica", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Granito", "Basalto", "Marmore", "Xisto"], category: "Rochas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Xilogravura", "Litografia", "Aguaforte", "Serigrafia"], category: "Tecnicas de gravura", difficulty: "medio", color: "#a0c35a" },
    { words: ["Foral", "Tombo", "Bula", "Diploma"], category: "Documentos historicos", difficulty: "medio", color: "#b0c4ef" },
    { words: ["Iris", "Voltaico", "Cego", "Triunfo"], category: "Seguem arco", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Argiloso", "Arenoso", "Calcario", "Humifero"], category: "Tipos de solo", difficulty: "facil", color: "#f9df6d" },
    { words: ["Azeitao", "Nisa", "Serpa", "Rabacal"], category: "Queijos portugueses", difficulty: "medio", color: "#a0c35a" },
    { words: ["Cumeeira", "Beiral", "Asna", "Ripado"], category: "Partes de um telhado", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Papiro", "Pergaminho", "Tabuinha", "Ostraco"], category: "Suportes de escrita antigos", difficulty: "dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Nascente", "Afluente", "Meandro", "Estuario"], category: "Elementos de um curso de agua", difficulty: "medio", color: "#f9df6d" },
    { words: ["Salga", "Fumagem", "Cura", "Escabeche"], category: "Conservacao de alimentos", difficulty: "medio", color: "#a0c35a" },
    { words: ["Clepsidra", "Ampulheta", "Gnomon", "Cronometro"], category: "Instrumentos para medir o tempo", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Tremonha", "Moega", "Rodizio", "Segurelha"], category: "Partes de um moinho tradicional", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Oleiro", "Roda", "Barro", "Forno"], category: "Oficina de ceramica", difficulty: "facil", color: "#f9df6d" },
    { words: ["Fisico", "Politico", "Topografico", "Tematico"], category: "Tipos de mapa", difficulty: "medio", color: "#a0c35a" },
    { words: ["Dorica", "Jonica", "Corintia", "Toscana"], category: "Ordens arquitetonicas classicas", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Ameia", "Baluarte", "Revelim", "Barbaca"], category: "Elementos de uma fortificacao", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Feijao", "Ervilha", "Lentilha", "Tremoco"], category: "Leguminosas", difficulty: "facil", color: "#f9df6d" },
    { words: ["Anta", "Menir", "Cromeleque", "Mamoa"], category: "Estruturas megaliticas", difficulty: "medio", color: "#a0c35a" },
    { words: ["Circo", "Morena", "Fiorde", "Drumlin"], category: "Formacoes glaciares", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Vilancete", "Sextina", "Rondel", "Vilanela"], category: "Formas poeticas fixas", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Mogno", "Faia", "Teca", "Ebano"], category: "Tipos de madeira", difficulty: "facil", color: "#f9df6d" },
    { words: ["Refracao", "Difracao", "Interferencia", "Dispersao"], category: "Fenomenos opticos", difficulty: "medio", color: "#a0c35a" },
    { words: ["Arcao", "Estribo", "Loros", "Cilha"], category: "Partes de uma sela", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Timbre", "Paquife", "Virol", "Lambel"], category: "Termos de heraldica", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Choco", "Lula", "Ostra", "Mexilhao"], category: "Moluscos marinhos", difficulty: "facil", color: "#f9df6d" },
    { words: ["Faianca", "Porcelana", "Gres", "Terracota"], category: "Materiais ceramicos", difficulty: "medio", color: "#a0c35a" },
    { words: ["Uncial", "Carolina", "Gotica", "Cursiva"], category: "Tipos de escrita antiga", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Lais", "Escota", "Catau", "Fateixa"], category: "Nos nauticos", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Rainha", "Obreira", "Zangao", "Favo"], category: "Numa colmeia", difficulty: "facil", color: "#f9df6d" },
    { words: ["Champinhao", "Cantarelo", "Miscaro", "Tubera"], category: "Cogumelos comestiveis", difficulty: "medio", color: "#a0c35a" },
    { words: ["Ogival", "Pleno", "Abatido", "Ferradura"], category: "Tipos de arco arquitetonico", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Garlopa", "Goiva", "Plaina", "Formao"], category: "Ferramentas de carpinteiro", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Barbo", "Boga", "Escalo", "Enguia"], category: "Peixes de rio em Portugal", difficulty: "facil", color: "#f9df6d" },
    { words: ["Tambor", "Escape", "Ancora", "Balanco"], category: "Mecanismo de um relogio", difficulty: "medio", color: "#a0c35a" },
    { words: ["Dorsal", "Fossa", "Planicie", "Talude"], category: "Relevo submarino", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Silhar", "Aduela", "Imposta", "Verga"], category: "Elementos de cantaria", difficulty: "muito dificil", color: "#ba81c5" },
  ],
  [
    { words: ["Pessego", "Ameixa", "Cereja", "Damasco"], category: "Frutos de caroco", difficulty: "facil", color: "#f9df6d" },
    { words: ["Alaude", "Bandolim", "Cavaquinho", "Citara"], category: "Instrumentos de corda dedilhada", difficulty: "medio", color: "#a0c35a" },
    { words: ["Pilrito", "Borrelho", "Macarico", "Tarambola"], category: "Aves limicolas", difficulty: "dificil", color: "#b0c4ef" },
    { words: ["Folio", "Rubrica", "Colofao", "Iluminura"], category: "Elementos de um manuscrito medieval", difficulty: "muito dificil", color: "#ba81c5" },
  ],
];
